version: "3"
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8099:80'
    container_name: app-cegah-terbaru
    env_file: .env.example